### ISSUE TITLE
Question: is this module compatible with jaeger?

### ISSUE THREAD

**Issue by aledbf** [rnburn/nginx-opentracing#7]
I see the traffic of the backend but not from nginx

**Comment by rnburn** [comment]
Jaeger doesn't have a [C++ client](https://github.com/jaegertracing/jaeger/issues/228) yet, so there's no direct support for it.

But I believe it has compatibility with the zipkin format so you might be able to make it work using the zipkin tracer.

**Comment by rnburn** [comment]
I put in a change to [zipkin-cpp-opentracing](https://github.com/rnburn/zipkin-cpp-opentracing/commit/de831a867c4c1f7b39d3951b03b852c82a796e9e) to support Jaeger.

I was using typed binary annotations which Jaeger doesn't support.

I also added an [example](https://github.com/rnburn/nginx-opentracing/tree/master/example/trivial) with instructions for how to set it up with Jaeger.

**Comment by aledbf** [comment]
@rnburn thank you!
