### ISSUE TITLE
Nginx 1.10.3 make error

### ISSUE THREAD

**Issue by One2r** [rnburn/nginx-opentracing#8]
Hi, I wanna install this module to my Nginx,but i got a error on the make step. My server environment infomations as below:

- OS : CentOS 7
   _cat /etc/redhat-release   ===>  CentOS Linux release 7.3.1611 (Core)_

- Nginx : nginx/1.10.3

and my install steps are:

1. _export NGINX_OPENTRACING_VENDOR="ZIPKIN"_
2. _./configure --prefix=/usr/local/nginx-1.10.3 --with-http_ssl_module --add-dynamic-module=/root/env/nginx-opentracing/opentracing --add-dynamic-module=/root/env/nginx-opentracing/zipkin_
this step (configure) is passed.
3. _make_
i got a error on this step.Error message as below:
_objs/src/http/modules/ngx_http_upstream_least_conn_module.o \
objs/src/http/modules/ngx_http_upstream_keepalive_module.o \
objs/src/http/modules/ngx_http_upstream_zone_module.o \
objs/ngx_modules.o \
-ldl -lpthread -lcrypt -lpcre -lssl -lcrypto -ldl -lz \
-Wl,-E
cc -c -fPIC -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  --std=c++11 -Wno-constexpr-not-const -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules \
	-o objs/addon/src/ngx_http_opentracing_module.o \
	/root/env/nginx-opentracing/opentracing/src/ngx_http_opentracing_module.cpp
/root/env/nginx-opentracing/opentracing/src/ngx_http_opentracing_module.cpp: In function ‘void* create_opentracing_main_conf(ngx_conf_t*)’:
/root/env/nginx-opentracing/opentracing/src/ngx_http_opentracing_module.cpp:107:40: error: missing initializer for member ‘ngx_opentracing::opentracing_main_conf_t::tags’ [-Werror=missing-field-initializers]
   *main_conf = opentracing_main_conf_t{};
                                        ^
At global scope:
cc1plus: error: unrecognized command line option "-Wno-constexpr-not-const" [-Werror]
cc1plus: all warnings being treated as errors
make[1]: *** [objs/addon/src/ngx_http_opentracing_module.o] Error 1
make[1]: Leaving directory `/root/env/nginx-1.10.3'
make: *** [build] Error 2_

So，is there something wrong on my install steps ? And can you help me fix this error ?

**Comment by rnburn** [comment]
The project moved to [opentracing-contrib/nginx-opentracing](https://github.com/opentracing-contrib/nginx-opentracing) BTW.

Do you know what compiler version you're using? Could you try running
```
gcc --version
```
it looks like it doesn't recognize the "-Wno-constexpr-not-const" option.

**Comment by rnburn** [comment]
Try setting
```
export CFLAGS="-Wno-error"
```
before running configure. I think that will let the compiler ignore the option it doesn't recognize.

**Comment by One2r** [comment]
@rnburn 
my compiler version ：
`gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)`

and i set 
`export CFLAGS="-Wno-error"`
before running configure，also can not make it pass.

**Comment by rnburn** [comment]
Could you try with the version at [opentracing-contrib/nginx-opentracing](https://github.com/opentracing-contrib/nginx-opentracing). I put in a change to remove the `-Wno-constexpr-not-const` option as I don't think it's needed anymore.

I don't know if you did, but you'll also need to build the zipkin library using
`cmake -DBUILD_SHARED_LIBS=1 ..` so that it produces a shared library instead of a static one.

**Comment by rnburn** [comment]
@One2r - were you able to get this to work?

**Comment by rnburn** [comment]
I put in some more workarounds for older compilers (https://github.com/opentracing-contrib/nginx-opentracing/pull/6) and tested against centos7/gcc4.8.5. It should work now. This is the docker file I used to build:
```
FROM centos
RUN set -x \
# install nginx-opentracing package dependencies
  && yum -y install \
            epel-release \
  && yum -y install \
            gcc \
            wget \
            git \
            cmake3 \
            curl-devel \
  && yum -y groupinstall "Development Tools" \
	&& tempDir="$(mktemp -d)" \
	&& chmod 777 "$tempDir" \
## Build opentracing-cpp
  && git clone https://github.com/opentracing/opentracing-cpp.git \
  && cd opentracing-cpp \
  && mkdir .build && cd .build \
  && cmake3 -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF .. \
  && make && make install \
  && cd "$tempDir" \
## Build zipkin-cpp-opentracing
  && git clone https://github.com/rnburn/zipkin-cpp-opentracing.git \
  && cd zipkin-cpp-opentracing \
  && mkdir .build && cd .build \
  && cmake3 -DBUILD_SHARED_LIBS=1 -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF .. \
  && make && make install \
  && cd "$tempDir" \
### Get nginx-opentracing source
  && git clone https://github.com/opentracing-contrib/nginx-opentracing.git \
## Build nginx
  && wget http://nginx.org/download/nginx-1.10.3.tar.gz \  
  && tar zxf nginx-1.10.3.tar.gz \
  && cd nginx-1.10.3 \
  && ./configure --prefix=/usr/local/nginx-1.10.3 \
                 --without-http_rewrite_module \
                 --without-http_gzip_module \
                 --add-dynamic-module=$tempDir/nginx-opentracing/opentracing \
                 --add-dynamic-module=$tempDir/nginx-opentracing/zipkin \
  && make && make install
```

**Comment by One2r** [comment]
i'm sorroy. i have to do some private things on this weekend,i will try again on next Monday.

**Comment by One2r** [comment]
@rnburn Yes , it's work now! And thank you very much!
